{
 "title": "Ecommerce Realtime Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Revenue for Top 10 Products",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT p_name as \"Product Name\", total_qty as \"Quantity\", total_revenue as \"Revenue\" FROM \"default\".\"_at_total_revenue_per_products\" ORDER BY total_revenue DESC LIMIT 10"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) as NumberOfOrders, toDate(created_at) as date from orders GROUP BY date; "
    }
   ]
  },
  {
   "type": "stat",
   "description": "Display the total selling products",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(total_qty) as \"Total Quantitity\" from _at_total_revenue_per_products;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) as \"Registered Users\" FROM users;"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT count(id) as \"number of product\",  created_at as time FROM orderdetails GROUP BY time LIMIT 1000;"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT city_name, latitude, longitude\r\nFROM orders\r\nJOIN addresses ON orders.address_id = addresses.id\r\nJOIN cities ON addresses.city_id = cities.id;\r\n"
    }
   ]
  },
  {
   "title": "Payment Methods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select payment_method_name, countMerge(order_count) as count from _at_number_of_orders_for_each_payment_method group by payment_method_name;"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT order_id, transaction_type, amount, status, created_at FROM transactions order by order_id DESC LIMIT 20;"
    }
   ]
  },
  {
   "title": "Number of Orders in Each Shipping Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT shipping_method_name, countMerge(order_count) as \"Number of Orders\"\r\nFROM _at_number_of_orders_for_each_shipping_method\r\nGROUP BY shipping_method_name\r\nORDER BY \"Number of Orders\" DESC;"
    }
   ]
  }
 ]
}